Updated Sudoku to v1.1
flipperdevices/flipper-application-catalog pull request #150
Opened 2023-09-14 18:55 UTC by profelis

# Application Submission

New version. Improved board generation algorithm

# Extra Requirements 

Nope

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

2023-09-15 10:01 UTC, doomwastaken commented
0.90.1 MPU fault, stack overflow
100% crashing on App startup

2023-09-15 13:00 UTC, profelis commented
> 0.90.1 MPU fault, stack overflow
> 100% crashing on App startup

did you tested with 4kb stack? because with 1kb is definitely stack overflow, but with 4k all ok. I tested it multiple times on device and never saw stackoverflow.

can I rerun this test locally or give me logs for example?

2023-09-15 20:34 UTC, profelis commented
I double-checked everything again. Starting with 3kb stack mem everything works perfect and only with 2kb stack I got the error - "MPU fault, possibly stack overflow".

2023-09-16 07:11 UTC, doomwastaken commented
Just make sure commit SHA is correct, if that is OK with you, I will try again once my temperature drops and I get to PC

2023-09-16 07:13 UTC, doomwastaken commented
I will try it again, odd, commit is correct and 4kb stack on it

2023-09-18 09:48 UTC, doomwastaken commented
This is extremely odd, took latest version for 91.4 release, still same MPU fault crash, stack overflow on launch

2023-09-18 12:19 UTC, hedger commented
Can confirm, it runs out of stack memory when generating new board:
```
#59 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x3, y=<optimized out>, y@entry=0x1) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#60 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x2, y=<optimized out>, y@entry=0x1) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#61 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x1, y=<optimized out>, y@entry=0x1) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#62 0x20010572 in solve_board (state=state@entry=0x2000f400, x=0x0, x@entry=0x9, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#63 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x8, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#64 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x7, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#65 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x6, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#66 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x5, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#67 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x4, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#68 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x3, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#69 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x2, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#70 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x1, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#71 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x0, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500
#72 0x200105cc in generate_board (state=0x2000f400) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:510
#73 start_game (state=state@entry=0x2000f400) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:520
#74 0x2001098c in sudoku_main (p=<optimized out>) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:586
#75 0x080578b0 in flipper_application_thread (context=0x2000f088) at lib/flipper_application/flipper_application.c:224
#76 0x08011a14 in furi_thread_body (context=0x2000f298) at furi/core/thread.c:90
#77 0x080119d2 in furi_thread_catch () at furi/core/thread.c:61
```

2023-09-18 17:59 UTC, hedger requested changes
Please either rework board validation or further increase stack size.

2023-09-18 19:59 UTC, profelis commented
I pushed 8kb stack, where are no problem with this. But I still think there is something wrong with your tests, because I have been testing this game on device last 6 days and everything was fine

2023-09-18 20:35 UTC, profelis commented
> Can confirm, it runs out of stack memory when generating new board:
> 
> ```
> #0  0x0800f59c in __furi_crash () at furi/core/check.c:166
> #1  0x080063e6 in MemManage_Handler () at firmware/targets/f7/furi_hal/furi_hal_interrupt.c:271
> #69 0x20010572 in solve_board (state=state@entry=0x2000f400, x=x@entry=0x2, y=<optimized out>, y@entry=0x0) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:500

> #72 0x200105cc in generate_board (state=0x2000f400) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:510
> #73 start_game (state=state@entry=0x2000f400) at /Users/hedger/work/fzapps/fz-sudoku/sudoku.c:520

and this callstack. 70 calls of solve_board, it's about 28bytes per call (3 int args, 2 local vars, stackbase + return address) = 1920bytes + previous few functions and you can get stack overflow, but only if you use a stack less then or equal 2kb.

2023-09-19 05:27 UTC, doomwastaken commented
> I pushed 8kb stack, where are no problem with this. But I still think there is something wrong with your tests, because I have been testing this game on device last 6 days and everything was fine

During tests we did 2 things, A) install app built by CI pipeline here, generated in actions -> run summary -> artifacts and B) build the fap from source code, checked that we were on main branch and on latest version. When running it on any flipper I had available, I was constantly crashing during app startup. Not much can go wrong there. I will test the newer version now. 

Also we had tried to go into app_data and remove all corresponding data to the app (second flipper was empty and not sure about state of Hedger devices)

2023-09-19 08:38 UTC, profelis commented
> > I was constantly crashing during app startup. Not much can go wrong there.

I don't understand how, I have device too and I tested on release and debug firmware multiple times, I tested with debug mode and without and always 3kb stack was enough and I set 4kb in advance to prevent some potential issues. 

I still believe that your test is wrong or your device is in special state (trace memory for example) which eats stack too and in result 4 kb is not enough. I wish that 8kb will be enough, but please, take a look on your test and fix it too.

2023-09-19 08:46 UTC, profelis commented
I just realised where is problem and it's odd again.

I used `dev` channel to update my ufbt utility `ufbt update --channel dev` and with this dev SDK all works perfect.

Right now I switched back to release `ufbt update --channel release` and got stack overflow too.

PS 8kb fix problem on release sdk.

2023-09-19 08:58 UTC, doomwastaken approved these changes

2023-09-19 08:59 UTC, doomwastaken approved these changes

2023-09-19 09:06 UTC, merged