Updated nupogodi to v1.2
flipperdevices/flipper-application-catalog pull request #158
Opened 2023-09-28 17:48 UTC by sionyx

# Application Submission

- Added more eggs at the same time to make game more complicate
- Increase Flipper level when collect 100 eggs.

# Author Checklist (Fill this out)

- [+] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [+] I own the code I'm submitting or have code owner's permission to submit it
- [-] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s)

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

2023-09-29 05:51 UTC, doomwastaken commented
@sionyx you need to add a short description to the package, it fails to build now

2023-10-02 16:35 UTC, doomwastaken requested changes
Please add short description, so we could pass CI pipeline

2023-10-03 00:37 UTC, hedger commented
Yes, please add fap_description to application.fam file.

2023-10-03 19:29 UTC, doomwastaken approved these changes

2023-10-03 19:29 UTC, merged