Update manifest.yml changed the Path of readme.md
flipperdevices/flipper-application-catalog pull request #209
Opened 2023-12-03 12:14 UTC by grugnoymeme

# Application Submission

- Updated readme PATH that was broken.

# Author Checklist (Fill this out)

- [x] I've read the [contribution guidelines](../blob/HEAD/documentation/Contributing.md) and my PR follows them
- [x] I own the code I'm submitting or have code owner's permission to submit it
- [x] I [have validated](../blob/HEAD/documentation/Contributing.md#validating-manifest) the manifest file(s) with `python3 tools/bundle.py --nolint applications/CATEGORY/APPID/manifest.yml bundle.zip`

# Reviewer Checklist (Don't fill this out)

- [ ] Bundle is valid
- [ ] There are no obvious issues with the source code
- [ ] I've ran this application and verified its functionality

2023-12-03 15:42 UTC, hedger requested changes
Please fill in the PR's description and fix manifest validation errors.

2023-12-05 16:52 UTC, grugnoymeme commented
> Please fill in the PR's description and fix manifest validation errors.

hey i cannot understand why its not working as this..

2023-12-22 07:47 UTC, hedger commented
Un-draft when fixed.

2024-11-03 09:24 UTC, doomwastaken commented
Currently it says that changelog is empty, add something to it

2025-01-23 06:51 UTC, doomwastaken commented
Converting it to draft, feel free to change it again, once fixed

2025-08-13 08:02 UTC, closed without merging